### ISSUE TITLE
React version does not seem to pick the options prop

### ISSUE THREAD

**Issue by anjanavarma** [jsGanttImproved/react-jsgantt#1]
Tried changing the options in the options prop. Does not seem to pick up the options.   
 <JSGantt data={data} options={{vEditable:1}} />
Please let me know if its the right way of passing in options. 
Tried below as well:
let editorOptions = [{
    vCaptionType: 'Complete',  // Set to Show Caption : None,Caption,Resource,Duration,Complete,
    vQuarterColWidth: 36,
    vDateTaskDisplayFormat: 'day dd month yyyy', // Shown in tool tip box
    vDayMajorDateDisplayFormat: 'mon yyyy - Week ww', // Set format to display dates in the "Major" header of the "Day" view
    vWeekMinorDateDisplayFormat: 'dd mon',
    vEditable: true
 }]
And,
 <JSGantt data={data} options={editorOptions} />

**Comment by jonathanlassen** [comment]
Fixed with #3, thank you for taking the time to submit the issue.

**Comment by mariohmol** [comment]
released on v 2.2.0 

thanks again @jonathanlassen !!

**Comment by thelowellgallery** [comment]
Anytime!

**Comment by jonathanlassen** [comment]
anytime!

**Comment by anjanavarma** [comment]
Thanks all !!
