### ISSUE TITLE
Error when build react-jsgantt 

### ISSUE THREAD

**Issue by AlanNggg** [jsGanttImproved/react-jsgantt#17]
When I forked this project and following the instructions below:

```sh
npm i -g rollup
npm install
cd example
npm install

```
I got a semantic error TS7016 Could not find a declaration file for module 'jsgantt-improved'. I overcame it by following https://stackoverflow.com/questions/41462729/typescript-react-could-not-find-a-declaration-file-for-module-react-material.
Also, when I compared the react-jsgantt I forked & react-jsgantt installed by npm, I found some difference between them, e.g. some css style is missing in react-jsgantt installed by npm. Is there any method to solve this problem?
Thanks

**Comment by HassanEmam** [comment]
I faced some problems while installing react-jsgantt and this was due to python2 not being my default python. Changed this in the environment variables in Windows and things worked as expected.

**Comment by siyabongaprospersithole** [comment]
Hi how can we solve this, i'm having the same issue

**Comment by mariohmol** [comment]
@jessegilbride , do you wanna try this one?

**Comment by mariohmol** [comment]
Thanks @HassanEmam , this is indeed a needed (python2)
I added that in the dev guide docs

thanks a lot
