### ISSUE TITLE
React-jsgantt shows gantt bars out of sync with timeline axis

### ISSUE THREAD

**Issue by ankurpiparsania** [jsGanttImproved/react-jsgantt#2]
Noted that react-jsgantt example as well as implementation shows the bars not in sync with the axis and doesnt match the start end dates correctly.

![image](https://user-images.githubusercontent.com/49896447/59026283-a6a5a180-8873-11e9-8aae-360e56f1308a.png)

**Comment by jonathanlassen** [comment]
confirmed that this is an issue with jsgant-improved, the issue was been transferred there https://github.com/jsGanttImproved/jsgantt-improved/issues/207

**Comment by mahmad2504** [comment]
I am also encountering this issue . But this happens only on Chrome and Opera . On IE and forefox same chart looks OK. Also this issue is prominent in large duration charts . Seems like it is a browser issue . Some offsets need to be added for Chrome and Opera browsers which will be kind of hack
