### ISSUE TITLE
Adding and setting custom language

### ISSUE THREAD

**Issue by tschinski** [jsGanttImproved/react-jsgantt#23]
Hey guys,

is there an equivalent function for

g.addLang('en2', en)
g.setLang('en2');

in react-jsgantt?

I didn't find a way to add a custom language or did i miss something?

Cheers Tobias

**Comment by mariohmol** [comment]
Hi
What language do u want to add?

we need something like this

https://github.com/jsGanttImproved/jsgantt-improved/issues/360
