### ISSUE TITLE
vTooltipTemplate

### ISSUE THREAD

**Issue by BellTree1212** [jsGanttImproved/react-jsgantt#5]
【question】
The date format cannot be set.<br>
I want to reflect the setting of vDateTaskDisplayFormat, what should I do?<br>
I want to display as "yyyy / mm / dd".
<br>
[example code]
`vTooltipTemplate: t => {
return '<div><span class="gTaskLabel">{{Lang:pStart}}:</span><span class="gTaskText">**{{pStart}}**</span></div>'
}`

**Comment by mariohmol** [comment]
this is easier to start @SeanBunch

**Comment by mariohmol** [comment]
@BellTree1212 , you can use the parameter task to get fields that you want.

for example: 
```js
    vTooltipTemplate: (t) => {
      const dateformated = new Date(t.getStart()).toLocaleDateString('en');
      return `<div><span class="gTaskLabel">{{Lang:pStart}}:</span><span class="gTaskText">**${dateformated}**</span></div>`;
    },
```

thanks!
