### ISSUE TITLE
The react-jsgantt example

### ISSUE THREAD

**Issue by ecke101** [jsGanttImproved/react-jsgantt#7]
I don't understand the example project. There are so many function that are never used somewhere. Maybe it could be updated to show better how to use react-jsgantt? For example how to fetch data from an API. Right now it feels like it would be much easier to just import the standard package?

**Comment by mariohmol** [comment]
this is a easy on to start @ShaneDFields

**Comment by mariohmol** [comment]
There is a stackblitz example on how to use it.. its a very simple wrapper indeed.. https://stackblitz.com/edit/react-jsgantt?file=App.tsx
